plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
filters:
  instance-state-name: running
#  tag:Environment:dev
keyed_groups:
  - key: tags.Name
hostnames:
  - private-ip-address
compose:
  ansible_host: private_ip_address
  ansible_user: ubuntu