- name: Setup Consul
  hosts: _dev_01_consul_instance  # or _stage_consul_instance
  become: yes
  gather_facts: yes
  vars:
    consul_user: consul
    consul_group: consul
    consul_data_dir: /opt/consul/data

  tasks:

    - name: Ensure consul user exists
      user:
        name: "{{ consul_user }}"
        shell: /bin/false
        system: yes
        state: present

    - name: Ensure Consul data directory exists
      file:
        path: "{{ consul_data_dir }}"
        state: directory
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '0755'

    - name: Deploy Consul config
      template:
        src: templates/consul_server.hcl.j2
        dest: /etc/consul.d/consul.hcl
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: '0644'
        

    - name: Deploy Consul systemd service
      template:
        src: templates/consul_server.service.j2
        dest: /etc/systemd/system/consul.service
        owner: root
        group: root
        mode: '0644'
        

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
        state: reloaded

    - name: Enable and start Consul
      systemd:
        name: consul
        state: started
        enabled: yes
