- name: Setup Consul
  hosts: _dev_01_nginx_load_balancer # or _stage_consul_instance
  become: yes
  gather_facts: yes
  vars:
    consul_user: consul
    consul_group: consul
    consul_data_dir: /opt/consul/data
    env_name: "{{ lookup('env','env_name') }}"

  tasks:
    - name: Ensure consul user exists
      user:
        name: '{{ consul_user }}'
        shell: /bin/false
        system: yes
        state: present

    - name: Ensure Consul data directory exists
      file:
        path: '{{ consul_data_dir }}'
        state: directory
        owner: '{{ consul_user }}'
        group: '{{ consul_group }}'
        mode: '0755'

    - name: Deploy Consul config
      template:
        src: templates/consul_lb_agent.hcl.j2
        dest: /etc/consul.d/lb.hcl
        owner: '{{ consul_user }}'
        group: '{{ consul_group }}'
        mode: '0644'

    - name: Deploy Consul systemd service
      template:
        src: templates/consul_lb_agent.service.j2
        dest: /etc/systemd/system/consul.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      command: systemctl daemon-reload
      become: yes

    - name: Enable and start Consul
      systemd:
        name: consul
        state: started
        enabled: yes

    - name: Deploy Consul-template config
      template:
        src: templates/consul_template_config.hcl.j2
        dest: /etc/consul.d/consul-template-config.hcl
        owner: '{{ consul_user }}'
        group: '{{ consul_group }}'
        mode: '0644'

    - name: Deploy Consul-template load-balancer config
      template:
        src: templates/load_balancer_template.hcl
        dest: /etc/nginx/load-balancer.conf.ctmpl
        owner: '{{ consul_user }}'
        group: '{{ consul_group }}'
        mode: '0644'

    - name: Deploy Consul-template systemd service
      template:
        src: templates/consul_template_lb_agent.service.j2
        dest: /etc/systemd/system/consul-template.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      command: systemctl daemon-reload
      become: yes

    - name: Enable and start Consul
      systemd:
        name: Consul-template
        state: started
        enabled: yes
