---
- name: Install PostgreSQL 14
  hosts: _dev-database-instance
  become: yes

  tasks:
    - name: Install postgresql
      apt:
        name:
          - postgresql-14
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: allow what IP address(es) to listen on;
      ansible.builtin.lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
      notify: Restart postgresql

    - name: allows authentication for all users connecting to all databases from any IPv4 address (0.0.0.0/0)
      ansible.builtin.lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        insertafter: EOF
        line: 'host    all             all             0.0.0.0/0               md5'
      notify: Restart postgresql

    - name: allow local postgres user authentication via password
      ansible.builtin.lineinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        insertafter: EOF
        line: 'local   all             postgres                                md5'
      notify: Restart postgresql

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL database
      postgresql_db:
        name: '{{ db_name }}'
        state: present
      become: yes
      become_user: postgres

    - name: Create PostgreSQL user db_user
      postgresql_user:
        name: '{{ db_user }}'
        password: '{{ db_pass }}'
        db: '{{ db_name }}'
        priv: 'ALL'
        state: present
      become: yes
      become_user: postgres

  handlers:
    - name: Restart postgresql
      service:
        name: postgresql
        state: restarted
