---
- name: Install and configure nginx + postgresql client
  hosts: _dev_webapp_asg_instance
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Copy Nginx configuration file
      template:
        src: templates/web_nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload Nginx

    - name: Install postgresql client
      apt:
        name: postgresql-client-14
        state: present

    - name: Copy frontend build
      copy:
        src: ../flask
        dest: .

    - name: Copy .env
      template:
        src: templates/.env.j2
        dest: flask/.env

    - name: Install systemd service for flaskbird
      template:
        src: templates/flaskbird.service.j2
        dest: /etc/systemd/system/flaskbird.service

    - name: Install packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-setuptools
          - python3-venv
          - gunicorn
        state: present
        update_cache: yes

    - name: Create venv and install requirements.txt
      ansible.builtin.pip:
        requirements: /home/ubuntu/flask/requirements.txt
        virtualenv: /home/ubuntu/flask/flasktest
        virtualenv_command: python3 -m venv flasktest
      become: yes

    - name: Run Flask database migrations
      command: /home/ubuntu/flask/flasktest/bin/flask db upgrade -d migrations
      args:
        chdir: /home/ubuntu/flask/birdproject
      become_user: ubuntu

    - name: Reload systemd
      command: systemctl daemon-reload
      become: yes

    - name: start flaskbird service
      service:
        name: flaskbird
        state: started

    - name: Change ownership of virtualenv
      ansible.builtin.file:
        path: /home/ubuntu/flask/flasktest
        owner: ubuntu
        group: ubuntu
        recurse: yes

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
