---
- name: Install and configure nginx + postgresql client
  hosts: web_servers
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy Nginx configuration file
      template:
        src: templates/web_nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload Nginx

    - name: Install postgresql client
      apt:
        name: postgresql-client-14
        state: present

    - name: Copy frontend build
      copy:
        src: ../week1/rhnatyshyn/flask
        dest: .

    - name: Copy .env
      template:
        src: templates/.env.j2
        dest: flask/.env

    - name: Install systemd service for flaskbird
      template:
        src: templates/flaskbird.service.j2
        dest: /etc/systemd/system/flaskbird.service

    - name: Install packages
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
          - python3-setuptools
          - python3-venv
          - gunicorn
        state: present
        update_cache: yes

    - name: Create venv and install requirements.txt
      ansible.builtin.pip:
        requirements: /home/vagrant/flask/requirements.txt
        virtualenv: /home/vagrant/flask/flasktest
        virtualenv_command: python3 -m venv flasktest
      become: yes

    - name: Create symlink for static folder
      ansible.builtin.file:
        src: /vagrant
        dest: /home/vagrant/flask/birdproject/static
        state: link

    - name: Reload systemd
      command: systemctl daemon-reload
      become: yes

    - name: start flaskbird service
      service:
        name: flaskbird
        state: started

    - name: Change ownership of virtualenv
      ansible.builtin.file:
        path: /home/vagrant/flask/flasktest
        owner: vagrant
        group: vagrant
        recurse: yes

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
